version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
# Look at permission denied error after run docker
# solution execute --> sudo chown -R $USER <directory>
